# Generated by Django 4.1.6 on 2023-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convFrom', models.CharField(max_length=10)),
                ('convRatio', models.FloatField(max_length=10)),
            ],
        ),
    ]
