# Generated by Django 4.1.6 on 2023-04-01 02:01

from django.db import migrations

def populate_db(apps, schema_editor):
    Conv = apps.get_model('unitconv', 'Conv')

    p = Conv(convFrom="lb", convRatio=14.583)
    p.save()

    t = Conv(convFrom="T", convRatio=32670)
    t.save()

    g = Conv(convFrom="g", convRatio=0.03215)
    g.save()

    toz= Conv(convFrom="t_oz", convRatio=1)
    toz.save()

    kg= Conv(convFrom="kg", convRatio=32.15)
    kg.save()

    oz = Conv(convFrom="oz", convRatio=0.911458)
    oz.save()



class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(populate_db)
    ]
